version: 2
jobs:
    build:
        docker:
            - image: circleci/node:11.6
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-
            - run:
                name: Install Packages
                command: npm install
            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
            - run:
                name: Lint Project
                command: npm run lint
            - run:
                name: Build Project
                command: npm run build --prod
    deploy:
        docker:
            - image: circleci/node:11.6
        working_directory: ~/repo
        steps:
            - run:
                name: Deploy Application
                command: echo "Deploying Application ..."

workflows:
    version: 2
    build-n-deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
