version: 2
orbs:
  heroku: circleci/heroku@1.0.0
jobs:
    build:
        docker:
            - image: circleci/node:11.6
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-
            - run:
                name: Install Packages
                command: npm install
            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
            - run:
                name: Lint Project
                command: npm run lint
            - run:
                name: Build Project
                command: npm run build --prod
    deploy:
        executor: heroku/default
        steps:
            - checkout
            - heroku/install
            - heroku/deploy-via-git:
                app-name: lazokin-recipe-book-angular

workflows:
    version: 2
    build-n-deploy:
        jobs:
            - build:
                filters:
                    tags:
                        only: /.*/
            - deploy:
                requires:
                    - build
                filters:
                    tags:
                        only: /v.*/
                    branches:
                        ignore: /.*/
